### ISSUE TITLE
requirement error

### ISSUE THREAD

**Issue by MustaphaDouch** [IvanGlinkin/Domain_checker#1]
### This Error:
    [ - ] Error: geoiplookup app is not installed. Execute "sudo apt-get install geoiplookup".
### Should be :
    [ - ] Error: geoiplookup app is not installed. Execute **"sudo apt-get install geoip-bin"**.
**And THANK YOU for this tool :)**

**Comment by IvanGlinkin** [comment]
Hi [MustaphaDouch](https://github.com/MustaphaDouch)
Thanks for the feedback. Fixed
```
# Fixed. Thanks t.me/@VladimirM89 and GitHub/@MustaphaDouch 
if ! which geoiplookup &> /dev/null; then
echo -e "$RED_BOLD[ - ]$CLEAR_FONT Error: "geoiplookup" app is not installed. Execute \"sudo apt-get install geoip-bin\""
exit 1
fi
```
